from pathlib import Path
import re
import requests
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Источники для объединения в custom-ru
SOURCES = {
    "custom-ru": [
        # antifilter-download-community: замени на нужный raw URL списка доменов
        "https://raw.githubusercontent.com/anticensority/runet-censorship-bypass/main/generated/domains.lst",
        # Re-filter-lists
        "https://raw.githubusercontent.com/1andrevich/Re-filter-lists/main/domains_all.lst",
    ],
    # category-ads: здесь пока берём ручной список в MANUAL ниже
    "category-ads": [],
}

MANUAL = {
    "category-ads": [
        "doubleclick.net",
        "googlesyndication.com",
        "googleadservices.com",
        "adservice.google.com",
        "adservice.google.ru",
        "googletagmanager.com",
        "googletagservices.com",
        "facebookadnetwork.com",
        "appsflyer.com",
    ],
    "telegram": [
        "telegram.org",
        "t.me",
        "telegra.ph",
        "tdesktop.com",
        "telegram.me",
    ],
    "viber": [
        "viber.com",
        "vb.me",
    ],
    "whatsapp": [
        "whatsapp.com",
        "whatsapp.net",
    ],
    "meta": [
        "meta.com",
    ],
    "facebook": [
        "facebook.com",
        "fb.com",
        "fbcdn.net",
        "fbsbx.com",
        "messenger.com",
        "accountkit.com",
    ],
    "google": [
        "google.com",
        "googleapis.com",
        "gstatic.com",
        "googlevideo.com",
        "ggpht.com",
        "youtube.com",
        "ytimg.com",
        "withgoogle.com",
    ],
    "supercell": [
        "supercell.com",
    ],
    "roblox": [
        "roblox.com",
        "rbxcdn.com",
    ],
}

DOMAIN_RE = re.compile(r"^(?:[a-z0-9-]+\.)+[a-z]{2,63}$")


def normalize_domain(line: str) -> str | None:
    line = line.strip().lower()

    if not line:
        return None
    if line.startswith("#") or line.startswith("//"):
        return None

    # убираем префиксы популярных форматов
    for prefix in ("full:", "domain:", "keyword:", "regexp:"):
        if line.startswith(prefix):
            line = line[len(prefix):].strip()

    line = line.replace("\t", " ").split(" ")[0].strip()

    # URL -> hostname
    if line.startswith("http://") or line.startswith("https://"):
        parsed = urlparse(line)
        line = parsed.hostname or ""

    line = line.strip().strip(".")
    if line.startswith("*."):
        line = line[2:]
    if line.startswith("."):
        line = line[1:]

    # отбрасываем порты и пути
    line = line.split("/")[0]
    if ":" in line and line.count(":") == 1:
        host, port = line.split(":", 1)
        if port.isdigit():
            line = host

    # фильтрация мусора
    if not line:
        return None
    if "_" in line:
        return None
    if line.endswith(".local"):
        return None

    return line if DOMAIN_RE.match(line) else None


def fetch_lines(url: str) -> list[str]:
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    return resp.text.splitlines()


def write_tag(tag: str, domains: set[str]) -> None:
    target = DATA_DIR / tag
    content = "\n".join(sorted(domains)) + "\n"
    target.write_text(content, encoding="utf-8")


def main() -> None:
    # Очищаем старые autogenerated-файлы
    if DATA_DIR.exists():
        for item in DATA_DIR.iterdir():
            if item.is_file():
                item.unlink()

    # Сборка тегов из удалённых источников
    for tag, urls in SOURCES.items():
        domains: set[str] = set()
        for url in urls:
            for line in fetch_lines(url):
                domain = normalize_domain(line)
                if domain:
                    domains.add(domain)
        write_tag(tag, domains)

    # Сборка тегов из ручных списков
    for tag, raw_domains in MANUAL.items():
        domains: set[str] = set()
        for item in raw_domains:
            domain = normalize_domain(item)
            if domain:
                domains.add(domain)
        write_tag(tag, domains)

    print("Done. Generated tags:")
    for file in sorted(DATA_DIR.iterdir()):
        if file.is_file():
            print(f"- {file.name}")


if __name__ == "__main__":
    main()
